import Header from "@/components/Header";
import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#050818] text-white">
      <div className="pointer-events-none fixed inset-0 overflow-hidden">
        <div className="absolute -left-32 -top-32 h-[600px] w-[600px] rounded-full bg-indigo-700/25 blur-[140px]" />
        <div className="absolute -right-32 top-24 h-[500px] w-[500px] rounded-full bg-cyan-600/15 blur-[140px]" />
      </div>
      <div className="relative mx-auto max-w-3xl px-5 py-8 md:px-10">
        <Header />
        <div className="mt-12 mb-16">
          <h1 className="text-4xl font-black text-white">Terms of Service</h1>
          <p className="mt-2 text-sm text-white/40">Last updated: May 2026</p>

          <div className="mt-10 space-y-10 text-sm leading-7 text-white/60">

            <section>
              <h2 className="mb-3 text-lg font-black text-white">1. Acceptance of terms</h2>
              <p>By accessing or using StudyPack.ai, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.</p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-black text-white">2. Description of service</h2>
              <p>StudyPack.ai is an AI powered study tool that generates premium study packs from lecture material uploaded by the user. We provide weekly study packs, exam packs, and language translation services on a credit basis.</p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-black text-white">3. User accounts</h2>
              <p>You must create an account to access paid features. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must be at least 16 years old to create an account.</p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-black text-white">4. Credits and payments</h2>
              <p>StudyPack.ai operates on a credit system. Credits are purchased in advance and deducted per generation. Credits do not expire and are non-refundable once a generation has successfully completed. If a generation fails, your credit is automatically refunded. All payments are processed securely via Stripe.</p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-black text-white">5. Uploaded content</h2>
              <p>You retain full ownership of any content you upload to StudyPack.ai. By uploading content, you grant us a limited licence to process that content solely for the purpose of generating your study pack. We do not share, sell, or use your uploaded content to train AI models. Uploaded files are deleted from our servers after processing.</p>
              <p className="mt-3">You are responsible for ensuring you have the right to upload any material to StudyPack.ai. By uploading content, you confirm that it is your own material or material you are permitted to use, and that you are using it for your personal study purposes only. StudyPack.ai processes uploaded content solely to generate original study notes — we do not reproduce, redistribute or publish your source material. Academic institutions may have their own policies regarding lecture recordings and transcripts; it is your responsibility to ensure your use complies with those policies.</p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-black text-white">6. Acceptable use</h2>
              <p>You agree not to use StudyPack.ai to upload content that is unlawful, defamatory, or infringes third-party intellectual property rights. You agree not to attempt to reverse engineer, scrape, or abuse our systems. Academic integrity is your responsibility — we provide study tools, not answers to submit as your own work.</p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-black text-white">7. Generated content</h2>
              <p>Study packs generated by StudyPack.ai are provided for personal educational use only. The content is AI generated and while we strive for accuracy, it should not be relied upon as a substitute for official course materials or professional advice. We make no guarantees regarding academic outcomes.</p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-black text-white">8. Limitation of liability</h2>
              <p>StudyPack.ai is provided on an "as is" basis. To the fullest extent permitted by law, we disclaim all warranties and shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-black text-white">9. Changes to terms</h2>
              <p>We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the updated terms. We will notify users of material changes via email where possible.</p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-black text-white">10. Contact</h2>
              <p>For questions about these terms, contact us at <a href="mailto:support@studypack.ai" className="text-indigo-400 hover:underline">support@studypack.ai</a> or via our <Link href="/contact" className="text-indigo-400 hover:underline">contact page</Link>.</p>
            </section>

          </div>
        </div>
      </div>
    </main>
  );
}
